### ISSUE TITLE
[GSSOC'23] Making navbar translucent 

### ISSUE THREAD

**Issue by purviporwal0** [AbhiPatel10/AISKCON-CONSTRUCTION#164]
I want to make nav bar translucent as it would look more attractive 
![Screenshot (7)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/116807722/0be10e9c-6c37-4daf-9ec5-74169c45c05f)

**Comment by kartikayasija** [comment]
Describe the solution by adding screenshots.

**Comment by kanikakaur27** [comment]
HI @kartikayasija @purviporwal0  Since the home page has a main theme image with a white background, I believe making the navbar translucent would not make much difference. Instead we can make the drop downs a bit translucent so that the animation/image below the drop-downs are not completely hidden. Another option can be to change the main image on the home page to something with a non-white background. Kindly allow me to work on this issue.

<img width="1439" alt="Screenshot 2023-05-25 at 10 52 38 PM" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/78797208/a4e615d6-e3ed-4338-89de-74d7ccc74a52">

<img width="1440" alt="Screenshot 2023-05-25 at 10 57 51 PM" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/78797208/1a5c425b-2e2c-423f-bea0-5fdecfda9981">

**Comment by kartikayasija** [comment]
Go ahead @kanikakaur27
